### ISSUE TITLE
Time-format support

### ISSUE THREAD

**Issue by glebovpavel** [glebovpavel/IR_to_MSExcel#13]
Now date in hh24:mi are shown in Excel as 00:00. That must be fixed.

**Comment by ma-schroeder** [comment]
Hi Pavel,

this is still not working unfortunately. I tested it on apex.oracle.com with plugin version 2.04.

This is the IR with HIREDATE with default data and my added column UPDATED (type is date and dateformat in apex is DD.MM.YYYY HH24:MI for both columns):

![1_ir](https://cloud.githubusercontent.com/assets/11662301/18741254/6102310e-80ae-11e6-9465-19054d9e3c84.jpg)

And this is the excel export:

![2_export](https://cloud.githubusercontent.com/assets/11662301/18741256/6537ed36-80ae-11e6-88ce-5893f75a19b9.jpg)

**Comment by glebovpavel** [comment]
@ma-schroeder Fixed in  2.10

**Comment by ma-schroeder** [comment]
Hi Pavel,

i am very sorry, but the error is still there with a german application setting:

![image](https://user-images.githubusercontent.com/11662301/27955507-67dfe3f0-6315-11e7-9b0e-693ca011b28f.png)

The export still shows 22.09.2016 0:00 like in the above screenshots.

But when i switch to "English (United States) (en-us)" in the application settings it actually works.

The databse colum is of type Date and the format mask of that column in the IR settings is "DD.MM.YYYY HH24:MI". I tested it on apex.oracle.com with APEX version 5.1.2 and locally on 5.1.1. I re-uploaded and executed the script "install_all_packages.sql" and imported the plugin-file from version 2.10

Btw. the Version still shows 2.08 unter Shared Components > Plugins.

**Comment by glebovpavel** [comment]
Hi Mathias,
thank you for quick-testing! 

send me please debug.txt like described in page 3 in Instructions.pdf.  
In last version i add additional logging for date/timestamp formats.
P.S. Unfortunately i can take a look at the problem only after 3 weeks...

Regards,
Pavel

**Comment by ma-schroeder** [comment]
Hi Pavel,

here is a zip-file with all three files:

- Excel.xlsx
- log.txt
- report_data.xml

[log_txt_and_xml_and_xlsx.zip](https://github.com/glebovpavel/IR_to_MSExcel/files/1131212/log_txt_and_xml_and_xlsx.zip)

Dont worry and thank you very much for this plugin!

Regards,
Mathias

**Comment by glebovpavel** [comment]
@ma-schroeder Hi, please take a look at the least version. Only IR_TO_XML.sql was really changed.

**Comment by ma-schroeder** [comment]
Hi Pavel,

nice, its working now. Thank you very much.

![image](https://user-images.githubusercontent.com/11662301/28519666-d33b3834-706c-11e7-8e7e-ad58f8175548.png)
