### ISSUE TITLE
Open Office opens file but shows no data.

### ISSUE THREAD

**Issue by JacoFourie** [glebovpavel/IR_to_MSExcel#51]
Thanks for a great plugin. We are now testing it on our new Apex 18.1 application we are building.
All works well on Windows using MS Office. But Open Office can open the file but it does not display any data.

If we open the file in Excel and then save it as a Excel file with another name then OpenOffice will open the file but not all the filters are there.

If we open the file in Excel and save it as a ods file then OpenOffice will open the file with all the data and filters in it.

We have users that use Linux desktops and they all use Open Office. It seems there is a small issue with the file format that is stopping Open Office to see the data.

**Comment by alexyegorov** [comment]
Also faced with this problem in Libre Office, after testing a bit found that the problem is with name of file xl/worksheets/sheet1.xml in Excel.xlsx archive, it should not be with capitalize "S". The line https://github.com/glebovpavel/IR_to_MSExcel/blob/15e0c8c7ee10e287302cdd41668be762e2228e86/IR_TO_XLSX.pkb#L2287

**Comment by glebovpavel** [comment]
@alexyegorov  Thank you very much! I will make a new version next days.

**Comment by alexyegorov** [comment]
thank you for your plugin, dude, updated my comment with some new info, take it into account

**Comment by glebovpavel** [comment]
Done in 3.16

**Comment by JacoFourie** [comment]
Hi. I still have the same error using 3.16. No data on Linux. Should it work now ?
